#pragma once

#include <Windows.h>
#include <stdint.h>

#define RGBA(r, g, b, a)  (COLORREF)((DWORD)((r)&0xff) | ((DWORD)((g)&0xff) << 8) | ((DWORD)((b)& 0xff) << 16) | ((DWORD)((a)&0xff) << 24))
#define GetAValue(rgba)   ((rgba >> 24) & 0xff)

#define COLOR_RGB_ALICE_BLUE              0xFFF8F0
#define COLOR_RGB_ANTIQUE_WHITE           0xD7EBFA
#define COLOR_RGB_AQUA                    0xFFFF00
#define COLOR_RGB_AQUAMARINE              0xD4FF7F
#define COLOR_RGB_AZURE                   0xFFFFF0
#define COLOR_RGB_BEIGE                   0xDCF5F5
#define COLOR_RGB_BISQUE                  0xC4E4FF
#define COLOR_RGB_BLACK                   0x000000
#define COLOR_RGB_BLANCHED_ALMOND         0xCDEBFF
#define COLOR_RGB_BLUE                    0xFF0000
#define COLOR_RGB_BLUE_VIOLET             0xE22B8A
#define COLOR_RGB_BROWN                   0x2A2AA5
#define COLOR_RGB_BURLY_WOOD              0x87B8DE
#define COLOR_RGB_CADET_BLUE              0xA09E5F
#define COLOR_RGB_CHARTREUSE              0x00FF7F
#define COLOR_RGB_CHOCOLATE               0x1E69D2
#define COLOR_RGB_CORAL                   0x507FFF
#define COLOR_RGB_CORNFLOWER_BLUE         0xED9564
#define COLOR_RGB_CORNSILK                0xDCF8FF
#define COLOR_RGB_CRIMSON                 0x3C14DC
#define COLOR_RGB_CYAN                    0xFFFF00
#define COLOR_RGB_DARK_BLUE               0x8B0000
#define COLOR_RGB_DARK_CYAN               0x8B8B00
#define COLOR_RGB_DARK_GOLDEN_ROD         0x0B86B8
#define COLOR_RGB_DARK_GRAY               0xA9A9A9
#define COLOR_RGB_DARK_GREEN              0x006400
#define COLOR_RGB_DARK_KHAKI              0x6BB7BD
#define COLOR_RGB_DARK_MAGENTA            0x8B008B
#define COLOR_RGB_DARK_OLIVE_GREEN        0x2F6B55
#define COLOR_RGB_DARK_ORANGE             0x008CFF
#define COLOR_RGB_DARK_ORCHID             0xCC3299
#define COLOR_RGB_DARK_RED                0x00008B
#define COLOR_RGB_DARK_SALMON             0x7A96E9
#define COLOR_RGB_DARK_SEA_GREEN          0x8FBC8F
#define COLOR_RGB_DARK_SLATE_BLUE         0x8B3D48
#define COLOR_RGB_DARK_SLATE_GRAY         0x4F4F2F
#define COLOR_RGB_DARK_TURQUOISE          0xD1CE00
#define COLOR_RGB_DARK_VIOLET             0xD30094
#define COLOR_RGB_DEEP_PINK               0x9314FF
#define COLOR_RGB_DEEP_SKY_BLUE           0xFFBF00
#define COLOR_RGB_DIM_GRAY                0x696969
#define COLOR_RGB_DODGER_BLUE             0xFF901E
#define COLOR_RGB_FIRE_BRICK              0x2222B2
#define COLOR_RGB_FLORAL_WHITE            0xF0FAFF
#define COLOR_RGB_FOREST_GREEN            0x228B22
#define COLOR_RGB_FUCHSIA                 0xFF00FF
#define COLOR_RGB_GAINGSBORO              0xDCDCDC
#define COLOR_RGB_GHOST_WHITE             0xFFF8F8
#define COLOR_RGB_GOLD                    0x00D7FF
#define COLOR_RGB_GOLDEN_ROD              0x20A5DA
#define COLOR_RGB_GRAY                    0x808080
#define COLOR_RGB_GREEN                   0x008000
#define COLOR_RGB_GREEN_YELLOW            0x2FFFAD
#define COLOR_RGB_HONEY_DEW               0xF0FFF0
#define COLOR_RGB_HOT_PINK                0xB469FF
#define COLOR_RGB_INDIAN_RED              0x5C5CCD
#define COLOR_RGB_INDIGO                  0x82004B
#define COLOR_RGB_IVORY                   0xF0FFFF
#define COLOR_RGB_KHAKI                   0x8CE6F0
#define COLOR_RGB_LAVENDER                0xFAE6E6
#define COLOR_RGB_LAVENDER_BLUSH          0xF5F0FF
#define COLOR_RGB_LAWN_GREEN              0x00FC7C
#define COLOR_RGB_LEMON_CHIFFON           0xCDFAFF
#define COLOR_RGB_LIGHT_BLUE              0xE6D8AD
#define COLOR_RGB_LIGHT_CORAL             0x8080F0
#define COLOR_RGB_LIGHT_CYAN              0xFFFFE0
#define COLOR_RGB_LIGHT_GOLDEN_ROW_YELLOW 0xD2FAFA
#define COLOR_RGB_LIGHT_GRAY              0xD3D3D3
#define COLOR_RGB_LIGHT_GREEN             0x90EE90
#define COLOR_RGB_LIGHT_PINK              0xC1B6FF
#define COLOR_RGB_LIGHT_SALMON            0x7AA0FF
#define COLOR_RGB_LIGHT_SEA_GREEN         0xAAB220
#define COLOR_RGB_LIGHT_SKY_BLUE          0xFACE87
#define COLOR_RGB_LIGHT_SLATE_GRAY        0x998877
#define COLOR_RGB_LIGHT_STEEL_BLUE        0xDEC4B0
#define COLOR_RGB_LIGHT_YELLOW            0xE0FFFF
#define COLOR_RGB_LIME                    0x00FF00
#define COLOR_RGB_LIME_GREEN              0x32CD32
#define COLOR_RGB_LINEN                   0xE6F0FA
#define COLOR_RGB_MAGENTA                 0xFF00FF
#define COLOR_RGB_Maroon                  0x000080
#define COLOR_RGB_MEDIUM_AQUA_MARINE      0xAACD66
#define COLOR_RGB_MEDIUM_BLUE             0xCD0000
#define COLOR_RGB_MEDIUM_ORCHID           0xD355BA
#define COLOR_RGB_MEDIUM_PURPLE           0xDB7093
#define COLOR_RGB_MEDIUM_SEA_GREEN        0x71B33C
#define COLOR_RGB_MEDIUM_SLATE_BLUE       0xEE687B
#define COLOR_RGB_MEDIUM_SPRING_GREEN     0x9AFA00
#define COLOR_RGB_MEDIUM_TURQUOISE        0xCCD148
#define COLOR_RGB_MEDIUM_VIOLET_RED       0x8515C7
#define COLOR_RGB_MIDNIGHT_BLUE           0x701919
#define COLOR_RGB_MINT_CREAM              0xFAFFF5
#define COLOR_RGB_MISTY_ROSE              0xE1E4FF
#define COLOR_RGB_MOCCASIN                0xB5E4FF
#define COLOR_RGB_NAVAJO_WHITE            0xADDEFF
#define COLOR_RGB_NAVY                    0x800000
#define COLOR_RGB_OLD_LACE                0xE6F5FD
#define COLOR_RGB_OLIVE                   0x008080
#define COLOR_RGB_OLIVE_DRAB              0x238E6B
#define COLOR_RGB_ORANGE                  0x00A5FF
#define COLOR_RGB_ORANGE_RED              0x0045FF
#define COLOR_RGB_ORCHID                  0xD670DA
#define COLOR_RGB_PALE_GOLDEN_ROD         0xAAE8EE
#define COLOR_RGB_PALE_GREEN              0x98FB98
#define COLOR_RGB_PALE_TURQUOISE          0xEEEEAF
#define COLOR_RGB_PALE_VIOLET_RED         0x9370DB
#define COLOR_RGB_PAPAYA_WHIP             0xD5EFFF
#define COLOR_RGB_PEACH_PUFF              0xB9DAFF
#define COLOR_RGB_PERU                    0x3F85CD
#define COLOR_RGB_PINK                    0xCBC0FF
#define COLOR_RGB_PLUM                    0xDDA0DD
#define COLOR_RGB_POWDER_BLUE             0xE6E0B0
#define COLOR_RGB_PURPLE                  0x800080
#define COLOR_RGB_REBECCA_PURPLE          0x993366
#define COLOR_RGB_RED                     0x0000FF
#define COLOR_RGB_ROSY_BROWN              0x8F8FBC
#define COLOR_RGB_ROYAL_BLUE              0xE16941
#define COLOR_RGB_SADDLE_BROWN            0x13458B
#define COLOR_RGB_SALMON                  0x7280FA
#define COLOR_RGB_SANDY_BROWN             0x60A4F4
#define COLOR_RGB_SEA_GREEN               0x578B2E
#define COLOR_RGB_SEA_SHELL               0xEEF5FF
#define COLOR_RGB_SIENNA                  0x2D52A0
#define COLOR_RGB_SILVER                  0xC0C0C0
#define COLOR_RGB_SKY_BLUE                0xEBCE87
#define COLOR_RGB_SLATE_BLUE              0xCD5A6A
#define COLOR_RGB_SLATE_GRAY              0x908070
#define COLOR_RGB_SNOW                    0xFAFAFF
#define COLOR_RGB_SPRING_GREEN            0x7FFF00
#define COLOR_RGB_STEEL_BLUE              0xB48246
#define COLOR_RGB_TAN                     0x8CB4D2
#define COLOR_RGB_TEAL                    0x808000
#define COLOR_RGB_THISTLE                 0xD8BFD8
#define COLOR_RGB_TOMATO                  0x4763FF
#define COLOR_RGB_TURQUOISE               0xD0E040
#define COLOR_RGB_VIOLET                  0xEE82EE
#define COLOR_RGB_WHEAT                   0xB3DEF5
#define COLOR_RGB_WHITE                   0xFFFFFF
#define COLOR_RGB_WHITE_SMOKE             0xF5F5F5
#define COLOR_RGB_YELLOW                  0x00FFFF
#define COLOR_RGB_YELLOW_GREEN            0x32CD9A